Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "main.py", line 23, in mainLoop
RuntimeError: input(): lost sys.stdin
